import Card from "../interfaces/card";

const cardsData: Card[] = [
  { rank: "2", suit: "CLUB", power: 13 },
  { rank: "3", suit: "CLUB", power: 1 },
  { rank: "4", suit: "CLUB", power: 2 },
  { rank: "5", suit: "CLUB", power: 3 },
  { rank: "6", suit: "CLUB", power: 4 },
  { rank: "7", suit: "CLUB", power: 5 },
  { rank: "8", suit: "CLUB", power: 6 },
  { rank: "9", suit: "CLUB", power: 7 },
  { rank: "10", suit: "CLUB", power: 8 },
  { rank: "J", suit: "CLUB", power: 9 },
  { rank: "Q", suit: "CLUB", power: 10 },
  { rank: "K", suit: "CLUB", power: 11 },
  { rank: "A", suit: "CLUB", power: 12 },

  { rank: "2", suit: "DIAMOND", power: 13 },
  { rank: "3", suit: "DIAMOND", power: 1 },
  { rank: "4", suit: "DIAMOND", power: 2 },
  { rank: "5", suit: "DIAMOND", power: 3 },
  { rank: "6", suit: "DIAMOND", power: 4 },
  { rank: "7", suit: "DIAMOND", power: 5 },
  { rank: "8", suit: "DIAMOND", power: 6 },
  { rank: "9", suit: "DIAMOND", power: 7 },
  { rank: "10", suit: "DIAMOND", power: 8 },
  { rank: "J", suit: "DIAMOND", power: 9 },
  { rank: "Q", suit: "DIAMOND", power: 10 },
  { rank: "K", suit: "DIAMOND", power: 11 },
  { rank: "A", suit: "DIAMOND", power: 12 },

  { rank: "2", suit: "HEART", power: 13 },
  { rank: "3", suit: "HEART", power: 1 },
  { rank: "4", suit: "HEART", power: 2 },
  { rank: "5", suit: "HEART", power: 3 },
  { rank: "6", suit: "HEART", power: 4 },
  { rank: "7", suit: "HEART", power: 5 },
  { rank: "8", suit: "HEART", power: 6 },
  { rank: "9", suit: "HEART", power: 7 },
  { rank: "10", suit: "HEART", power: 8 },
  { rank: "J", suit: "HEART", power: 9 },
  { rank: "Q", suit: "HEART", power: 10 },
  { rank: "K", suit: "HEART", power: 11 },
  { rank: "A", suit: "HEART", power: 12 },

  { rank: "2", suit: "SPADE", power: 13 },
  { rank: "3", suit: "SPADE", power: 1 },
  { rank: "4", suit: "SPADE", power: 2 },
  { rank: "5", suit: "SPADE", power: 3 },
  { rank: "6", suit: "SPADE", power: 4 },
  { rank: "7", suit: "SPADE", power: 5 },
  { rank: "8", suit: "SPADE", power: 6 },
  { rank: "9", suit: "SPADE", power: 7 },
  { rank: "10", suit: "SPADE", power: 8 },
  { rank: "J", suit: "SPADE", power: 9 },
  { rank: "Q", suit: "SPADE", power: 10 },
  { rank: "K", suit: "SPADE", power: 11 },
  { rank: "A", suit: "SPADE", power: 12 }
];

export default cardsData;
